GET http://192.168.35.29:3000/api/extract-token
Authorization: Bearer eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..gyRvbSG-0vuhDX8j.0OVYznyQM6UMkkvZROAqZ9ZTo01t1KhjRuonRY7wgb4wSMZfnG_4NCNr3e9roYBt02xT296r5QejOSCq8ze5Kg8I9wjDQ8gG502KsT2P0INBaJSNVB93uYZJn5NfyiZO3U0Sz49uCVZCFOZdoQyuJvqbMc-jKsWRiWR8B8oKWcTQ5sl0m91wo9F1djJ7V6k1lbL_rB-lTwew4DEaUkJCsbYJ.jIJpqoBAdHGNY-7CDEeaWw

###
GET http://192.168.35.29:3000/api/protected

###
GET http://192.168.35.29:3000/api/protected
Authorization: Bearer eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..gyRvbSG-0vuhDX8j.0OVYznyQM6UMkkvZROAqZ9ZTo01t1KhjRuonRY7wgb4wSMZfnG_4NCNr3e9roYBt02xT296r5QejOSCq8ze5Kg8I9wjDQ8gG502KsT2P0INBaJSNVB93uYZJn5NfyiZO3U0Sz49uCVZCFOZdoQyuJvqbMc-jKsWRiWR8B8oKWcTQ5sl0m91wo9F1djJ7V6k1lbL_rB-lTwew4DEaUkJCsbYJ.jIJpqoBAdHGNY-7CDEeaWw

###
GET http://192.168.35.29:3000/api/hello
